### ISSUE TITLE
Update  README File 

### ISSUE THREAD

**Issue by badal-cloud** [badal-cloud/Know-Your-Bed#9]
1. Add More unique and Technical tag in Readme.
2. Add some content regarding Technology using in Project .

**Comment by hambali999** [comment]
Hi i have made changes, please merge my PR, #11

**Comment by hambali999** [comment]
Hi is this eligible for hacktoberfest? please label "hacktoberfest-accepted" instead of "hactoberfest-accepted", i think u miss a 'k' there
